from .test___init__ import TestAnalyzerInit
from .test__parse_grades import TestAnalyzerParseGrades
from .test__parse_name import TestAnalyzerParseName
from .test__parse_photos import TestAnalyzerParsePhotos
from .test_process_text import TestAnalyzerProcessText
from .test_analyze import TestAnalyzerAnalyze
